#!/bin/bash
cmd=$1
if [ -z "$cmd" ];then
	echo "参数为空。请重新输入"
	exit -1
fi
for index in master slave01 slave02 slave03
do
	result=`ssh ${index} "source ~/.profile;${cmd}"`
	res=`echo $result | awk -F " " '{print NF}'`
	
	echo "--------------------${index}--------------------"
	if [ "${cmd}" == "jps" ];then
		echo $result |  awk -F " " 'BEGIN{i=1} {while(i<=NF) print $i,$(i+1),i=i+2}' | awk -F " " '{print $1 " " $2 }'
	else
		echo $result |  awk -F " " 'BEGIN{i=1} {while(i<=NF) print $i,i=i+1}' | awk -F " " '{print $1 }'
	fi
	#记录日志
	echo -e "------------------${index}执行${cmd}后产生的日志------------------\n时间:`date`\n$result\n" >> ~/xcall.log
done
